spring:
  application:
    name: cloudStorage
  datasource:
    url: jdbc:mariadb://localhost:3306/cloud_storage_db
    username: main
    password: 12345qwert
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: localhost
      port: 6379
  liquibase:
    change-log: classpath:db/changelog/migrationsTables.yml
  logging:
    level:
      org.springframework.security: DEBUG
  mvc:
    view:
      prefix: /resources/templates

